
disabled_rules:
  - identifier_name
  - line_length
  - switch_case_alignment
  - multiple_closures_with_trailing_closure
  - multiline_function_chains
  - function_parameter_count
  - multiline_parameters_brackets
opt_in_rules:
  - closure_spacing
  - closure_end_indentation
  - collection_alignment
  - multiline_function_chains
  - multiline_parameters_brackets
  - unused_import
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - literal_expression_end_indentation

included: # paths to include during linting. `--path` is ignored if present.
  - Temple Beasts
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Temple Beasts/Assets.xcassets
